apiVersion: v1
kind: Service
metadata:
  name: oreilly-library-service
spec:
  selector:
    app: oreilly-library
  ports:
  - protocol: "TCP"
    port: 8000
    targetPort: 5000
  type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oreilly-library
  labels:
    app: oreilly-library
spec:
  replicas: 4
  selector:
    matchLabels:
      app: oreilly-library
  template:
    metadata:
      labels:
        app: oreilly-library
    spec:
      containers:
      - name: oreilly-library
        image: oreilly-library:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        