---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oreilly-library-deployment
  labels:
    app: oreilly-library
spec:
  replicas: 3
  selector:
    matchLabels:
      app: oreilly-library
  template:
    metadata:
      labels:
        app: oreilly-library
    spec:
      containers:
        - name: oreilly-library
          image: oreilly-library:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: db_root_password
              valueFrom:
                secretKeyRef:
                  name: flaskapi-secrets
                  key: db_root_password
            - name: db_name
              value: BookLibrary

---
apiVersion: v1
kind: Service
metadata:
  name: oreilly-library-service
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: oreilly-library
  type: LoadBalancer